### PR TITLE
Add a link to the phone number google spreadsheet

### PR DESCRIPTION
**Pull request by c-lliope**

### CODE REVIEW

**Comment by c-lliope** [comment]
What's the policy on sharing google documents that may contain sensitive information?

The phone list spreadsheet is marked as "Anyone with the link can view". CfA staff phone numbers are sensitive information, and it probably isn't wise to post the link in the github source. Thoughts on ways to get around this?

**Comment by c-lliope** [comment]
thinking about this a bit more, the simplest solution would probably be to change the permissions of the google doc so that only CfA members can view it. Who would I talk to about that?

**Comment by davidrleonard** [comment]
@graysonwright I would chat with Carolina about our policy on sharing Google Docs. Depending on what she says you could move forward with changing permissions/adding a link to c4a.

**Comment by c-lliope** [comment]
cleared it with Carolina - I updated the permissions for the google doc so that only people within CfA can access it.

**Pull request merged**
